### ISSUE TITLE
New version of CocoaPods

### ISSUE THREAD

**Issue by marcovanetti** [liviur/LRGooglePlusClient#1]
With the new version of cocoa pods 

`#import <google-plus-ios-sdk/GooglePlus.h>`

doesn't work.
So, instead of

`#ifdef COCOAPODS`
`#import <google-plus-ios-sdk/GooglePlus.h>`
`#else`
`#import <GooglePlus/GooglePlus.h>`
`#endif`

you can just use

`#import <GooglePlus/GooglePlus.h>`

**Comment by liviur** [comment]
Hey @marcovanetti - Care to point me to the file so I can properly update it?

Thanks!

**Comment by liviur** [comment]
Nevermind - got it :+1: I'll fix it and release a new version.

**Comment by marcovanetti** [comment]
All the imports between

`#ifdef COCOAPODS` and `#else`

are broken. You can just try to update cocoa pods to figure out the problem :+1:

**Comment by liviur** [comment]
Google plus changed their podspec for this without updating a version :-1: 
Anyhow - the change makes sense anyway and it unifies a stupid behaviour that was there up till this point.

I created version 1.2.0.

Please let me know if there still is an issue now. If so - I'll re-open.
